### PR TITLE
modify: Add an extra function user_local_modify for end users to popu…

### PR DESCRIPTION
**Pull request by drewmoseley**
…late.

Changelog: Title
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
I use this with a local mender_local_config file to populate extra files needed for Raspbian headless configuration.  Very useful for things like enabling uart and providing Wifi credentials

**Comment by drewmoseley** [comment]
Looks like the service file name changed upstream for some reason.  Need to rename it mender-client.

**Comment by lluiscampos** [comment]
> Looks like the service file name changed upstream for some reason. Need to rename it mender-client.

Yes. We changed it in the last updates on the Debian package and we didn't follow up in this repo. Good catch.

**Comment by mirzak** [comment]
@lluiscampos , any idea on the gitlab errors? Something has changed in the infrastructure it seems?

**Comment by lluiscampos** [comment]
It seems to be an infra problem with the acceptance tests. I am looking into it.

**Comment by lluiscampos** [comment]
> It seems to be an infra problem with the acceptance tests. I am looking into it.

Fixed independently in #134

**Comment by lluiscampos** [comment]
> @lluiscampos , any idea on the gitlab errors? Something has changed in the infrastructure it seems?
> 
> Do we need to run with `python3` now?
> 
> https://github.com/mendersoftware/mender-convert/blob/next/scripts/run-tests.sh#L102

(sorry I missed your comment before, seems like we were typing at the same time).

What happened is that `meta-mender` master has been updated for Python 3 but `mender-convert` has been left behind. See JIRA [QA-120](https://tracker.mender.io/browse/QA-120)

**Comment by mirzak** [comment]
Why do we not just run the tests using `python3`? As far as I understand it, there are no specific tests for mender-convert, and we are just pulling the existing tests used by meta-mender which should have been ported to python3 already?

Yes we are typing at the same time :)

**Comment by lluiscampos** [comment]
> Why do we not just run the tests using `python3`? As far as I understand it, there are no specific tests for mender-convert, and we are just pulling the existing tests used by meta-mender which should have been ported to python3 already?

While looking at the ticket now I also had the same idea: QA-120 is way over estimated and the actual work is only to update the submodule and revert #134... I think I will just do it straight away! I'll rework the other PR :)

**Comment by lluiscampos** [comment]
New PR to update tests to Python3. See #135

**Comment by lluiscampos** [comment]
@drewmoseley Can you please rebase this PR on top of latest next? The Pipeline should now run properly.

**Comment by drewmoseley** [comment]
Rebased

**Pull request merged**
