### PR TITLE
Use consistent compression and archive naming.

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
Note that this will require an update of the stored binaries.  And I don't think we have the rockpro sources yet in uboot-mender.

**Comment by drewmoseley** [comment]
I actually had the fixes to mender-convert-integration-scripts locally but forgot to submit them. See https://github.com/mendersoftware/mender-convert-integration-scripts/pull/7

**Comment by drewmoseley** [comment]
Regarding ROCKPRO, before this commit they were extracted with "tar xvf" but now it is "tar xzvf" so I suspect that will fail if the binaries are not repackaged.

**Comment by lluiscampos** [comment]
> Regarding ROCKPRO, before this commit they were extracted with "tar xvf" but now it is "tar xzvf" so I suspect that will fail if the binaries are not repackaged.

That is correct. I will manually update them as I said in `mender-convert-integration-scripts` PR

**Comment by lluiscampos** [comment]
See also https://github.com/mendersoftware/mender-convert-integration-scripts/pull/7

**Comment by lluiscampos** [comment]
The problem now is that once we merge `mender-convert-integration-scripts` PR, the already tagged mender-convert 2.0.0b1 will stop working, as some of the files use the same extension but now properly compressed.

I am thinking on waiting with these two PRs for one week more, and merge them just few days before final release.

What do you think @kacf and others?

**Comment by kacf** [comment]
But it will not delete already uploaded binaries, will it?

**Comment by lluiscampos** [comment]
> But it will not delete already uploaded binaries, will it?

Yes, it will. For example for [RPi u-boot](https://github.com/mendersoftware/mender-convert-integration-scripts/pull/7/files#diff-ec9076aed12a7e7bfd82c71de8cc2f80) or for [GRUB EFI](https://github.com/mendersoftware/mender-convert-integration-scripts/pull/7/files#diff-286f7969d4606fbe29e1ff6e9b0f5239), the files will have the same extension (same filename) but now properly compressed.

**Comment by kacf** [comment]
Ah right, some even have the same name. Then I agree, let's merge this as late as we can basically. Make sure this is on the list of blockers or in the release checklist for 2.3.0!

**Comment by lluiscampos** [comment]
> Ah right, some even have the same name. Then I agree, let's merge this as late as we can basically. Make sure this is on the list of blockers or in the release checklist for 2.3.0!

@kacf Good suggestion. I created a JIRA ticket for it, ref https://tracker.mender.io/browse/MEN-3202

@drewmoseley So the decision is to not merge this until end of next week. However this PR needs a rebase and conflict resolution. I can take over if you don't have the time.

**Comment by drewmoseley** [comment]
@lluiscampos rebased.

**Pull request merged**
