### PR TITLE
[test-utils.sh] Clean the pip list + grep command

### PR DESCRIPTION
**Pull request by lluiscampos**
So that we clean the deprecation warning and the multiple errors when
calling this command from CI.

### CODE REVIEW

**Comment by lluiscampos** [comment]
See the current warning/erros in latest run from master [here](https://gitlab.com/Northern.tech/Mender/mender-convert/-/jobs/736357295).

**Review by oleorhagen — APPROVED** [review]

**Comment by lluiscampos** [comment]
The warning disappeared but the [errors are still there](https://gitlab.com/Northern.tech/Mender/mender-convert/-/jobs/741013715). @oleorhagen do you have any suggestion?

**Comment by oleorhagen** [comment]
The issue is that `grep` exits immediately upon finding a match when run with `-q`, I think :)

**Comment by lluiscampos** [comment]
> The issue is that `grep` exits immediately upon finding a match when run with `-q`, I think :)

Thanks. Trying that :)

**Pull request merged**
