### PR TITLE
Reorganize RPi files

### PR DESCRIPTION
**Pull request by ghost**
```
commit fd1692e75cdd6a8cd12c48feb27cbd564910bdba
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Tue Nov 5 14:49:52 2024

    chore: Remove config that doesn't belong the raspberrypi files.
    
    It's already the default, and is not really related to Raspberry Pi.
    
    Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

commit 90ffa630874ac1b7da16efc200f96ff4694393b5
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Thu Nov 7 10:29:06 2024

    refac: Reorganize RPi configs and put into sub folders.
    
    Changelog: Raspberry Pi configs have changed names. Please see the
    `README.md` files for the new names.
    
    Ticket: None
    
    Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

commit 84ac1d2374d977fb111dfde1ce3bb15f56c2a3fc
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Tue Nov 5 08:23:07 2024

    chore: Move versioned URL into config file.
    
    Gives a bit more visibility than having it inline in the code.
    
    Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
```

### CODE REVIEW

**Comment by kacf** [comment]
@TheYoctoJester: Almost all of this is just moving code around, so I highly recommend viewing locally with `--color-moved`. Makes it much easier to read. 🙂

**Comment by kacf** [comment]
@lluiscampos: I'm mainly pinging you for the `.gitlab-ci.yml` part.

**Comment by kacf** [comment]
> Nitpick: I would call it `RASPBERRYPI_BASE_CONFIG` (as opposed to `RASPBERRYPI_BARE_CONFIG`), but that's just me maybe.

I thought about this when I first named it. I was trying to convey that it's not a "smaller" or "different" config, just the same config expressed as a bare name. But I dunno... Let's see what Lluis says, if he has the same opinion, I'll change it.

**Review by lluiscampos — APPROVED** [review]
I also think that `_BASE_` is better.

The CI file looks good :+1:

**Comment by lluiscampos** [comment]
> (...) I was trying to convey that it's not a "smaller" or "different" config, (...)

Right, but we use the `basename` command to get it :thinking:

**Comment by kacf** [comment]
> > (...) I was trying to convey that it's not a "smaller" or "different" config, (...)
> 
> Right, but we use the `basename` command to get it 🤔

Yes, but `basename` does produce something smaller, out of a larger path.

Anyway, we're splitting hairs here, the gut feeling of two people is enough to change it! 😄

**Comment by lluiscampos** [comment]
> Yes, but `basename` does produce something smaller, out of a larger path.

What if we use `RASPBERRYPI_CONFIG_NAME` then?

(I see you already force-pushed, so likely not worth a second rename :sweat_smile: )

**Comment by kacf** [comment]
> > Yes, but `basename` does produce something smaller, out of a larger path.
> 
> What if we use `RASPBERRYPI_CONFIG_NAME` then?
> 
> (I see you already force-pushed, so likely not worth a second rename 😅 )

I like it, it's more distinctive. Sorry, Gitlab, I have to bother you some more then!

**Pull request merged**
