### PR TITLE
chore(linkbot): Start monitoring the bullseye-minimal-hf imgs

### PR DESCRIPTION
**Pull request by oleorhagen**
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by kacf — APPROVED** [review]
Failure should be spurious, the one fixed by https://github.com/mendersoftware/mender-image-tests/pull/73. Let me know if I should merge.

**Comment by oleorhagen** [comment]
> Failure should be spurious, the one fixed by [mendersoftware/mender-image-tests#73](https://github.com/mendersoftware/mender-image-tests/pull/73). Let me know if I should merge.

Please do :)

**Comment by kacf** [comment]
Uhm, hold on. The image doesn't work. See [QA-467](https://tracker.mender.io/browse/QA-467). I think we have to disable this instead.

**Comment by oleorhagen** [comment]
> Uhm, hold on. The image doesn't work. See [QA-467](https://tracker.mender.io/browse/QA-467). I think we have to disable this instead.

HOly moly

**Pull request closed without merging**
