### PR TITLE
Check a Linux ext4 file system before resizing 'primary' partition

### PR DESCRIPTION
**Pull request by apodogrocki**
Issues: MEN-2242

Changelog: Title

Signed-off-by: Adam Podogrocki <a.podogrocki@gmail.com>

### CODE REVIEW

**Comment by apodogrocki** [comment]
@mirzak One more question: what about 'secondary' partition? Its physical size is modified, file system is left untouched. Is it update process responsibility to take care about file system when rootfs B is flashed?

**Comment by mirzak** [comment]
> Is it update process responsibility to take care about file system when rootfs B is flashed?

Yes it is depended on how you generate the artifact. I have not verified that part yet, but we can double check that the .mender content has the correct size. Which I assume it has as you extract the image from "primary" right?

**Comment by mirzak** [comment]
> Which I assume it has as you extract the image from "primary" right?

Checked the .mender file, it contains a resized ext4. All is good.

**Comment by apodogrocki** [comment]
:+1:

**Pull request merged**
