### PR TITLE
configs: Added centos x86-64 hdd defconfig

### PR DESCRIPTION
**Pull request by nandra**
Changelog: Title

Setup for converting CentOS Linux 8 (test device was used Intel NUC)
with 128G SSD.

Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>

### CODE REVIEW

**Comment by nandra** [comment]
Just thinking if won't be better to create one generic x86 defconfig. This config is same just image name is different. Open to suggestions. Thanks.

**Comment by kacf** [comment]
Yes, I'm thinking the same thing. x86 should be pretty uniform.

**Comment by nandra** [comment]
@kacf updated. Thanks.

**Comment by kacf** [comment]
Thanks, @nandra!

**Pull request merged**
