### PR TITLE
docs/device-image-shell: add qemu-user-static requirement info

### PR DESCRIPTION
**Pull request by mkozjak**

### CODE REVIEW

**Comment by oleorhagen** [comment]
Hi @mkozjak, and welcome to the Mender project :)
Contributing to the project requries a sign-off commit, due to legalities (read: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for). This can be done by running `git commit --amend --signoff`. Travis error:

**Comment by mkozjak** [comment]
@oleorhagen: Done.

**Comment by oleorhagen** [comment]
Hi @mkozjak :)

```
0.02s$ mendertesting/check_commits.sh
Checking range: master..HEAD:
commit 67ae4c4ea55344cfbf87f87368e7413161872687 (HEAD)
Merge: 0328167 443d928
Author: Mario Kozjak <kozjakm1@gmail.com>
Date:   Fri Jul 26 08:46:13 2019 +0000
    Merge 443d9282c467d70a6f71fd4f46d7df4742edc227 into 03281673e6e59c04accb331e5eb92767d3de2056
commit 443d9282c467d70a6f71fd4f46d7df4742edc227
Merge: 466ca80 a49ba8b
Author: Mario Kozjak <kozjakm1@gmail.com>
Date:   Fri Jul 26 10:46:01 2019 +0200
    Merge branch 'patch-1' of https://github.com/mkozjak/mender-convert into patch-1
commit 466ca80a47539ba51e12f6a953b83af1ba483895
Author: Mario Kozjak <kozjakm1@gmail.com>
Date:   Sun Jul 21 20:52:28 2019 +0200
    device-image-shell: qemu-user-static info
    
    Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>
commit a49ba8bf3d196db7ce8d0b319074a83a631de600
Author: Mario Kozjak <kozjakm1@gmail.com>
Date:   Sun Jul 21 20:52:28 2019 +0200
    device-image-shell: qemu-user-static info
Commit 466ca80a47539ba51e12f6a953b83af1ba483895 doesn't have a changelog tag! Make a changelog entry for your commit (https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags).
Commit a49ba8bf3d196db7ce8d0b319074a83a631de600 is not signed off! Use --signoff with your commit.
Commit a49ba8bf3d196db7ce8d0b319074a83a631de600 doesn't have a changelog tag! Make a changelog entry for your commit (https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#changelog-tags).
The command "mendertesting/check_commits.sh" exited with 1.
```
We're nearly there :) It looks like you have successfully signed your last two commits, which means that you are doing it right. However, I will need to extract some more git wizardry from you.

Three commits are a little much for this little change, so if you could either:
1) Squash your commits into one, and have it signed
2) Checkout the original commit and amend and sign it off :)

Then force push :)

Does that make sense? 

- Ole

**Comment by mkozjak** [comment]
@oleorhagen: Like this?

**Comment by oleorhagen** [comment]
Yes! 

Now only the `Changelog` tag is missing. 

This one is easy

Simply reword your commit, with a single line in the body having:

`Changelog: None`

Then we are done :)

**Comment by mkozjak** [comment]
This was hectic.

**Comment by oleorhagen** [comment]
Beautiful!

Yeh, I know it can be a little involved, I'm sry. However, take comfort in knowing that this is pretty common in most open source projects, and hence now you are prepared to contribute basically anywhere :)

Thank you for your patience ^^

**Pull request merged**
