### PR TITLE
Remove the 'only' tag from the publish job

### PR DESCRIPTION
**Pull request by oleorhagen**
It is already manual, so really no need for the 'only' tag.

Changelog: None

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
I disagree, I don't think this is a good idea.

As the deliverable here is identified only by the mender client version, with this change we basically allow for any dev branch to override production deliverables.

@oleorhagen Could you elaborate in why did you need this with the ongoing release?

**Comment by oleorhagen** [comment]
> I disagree, I don't think this is a good idea.
> 
> As the deliverable here is identified only by the mender client version, with this change we basically allow for any dev branch to override production deliverables.
> 
> @oleorhagen Could you elaborate in why did you need this with the ongoing release?

Because I wanted to run this with the release candidate: `<release>-build'n'`.
Another option could be to add this to the only tag.

Are we completely off here?

**Comment by lluiscampos** [comment]
@oleorhagen I see. But `MENDER_VERSION` can still be `<release>-build'n'` (in the GitLab variables and/or in the code) while `mender-convert` is `2.2.x`, hence still being published from a verified and reviewed branch. This is how I have done it previously.

**Comment by lluiscampos** [comment]
@oleorhagen Alternatively, I would have extended the current only regex to add the `-buildXX` suffix. In any case what I want to avoid is publishing from arbitrary branches.

**Comment by oleorhagen** [comment]
> @oleorhagen I see. But `MENDER_VERSION` can still be `<release>-build'n'` (in the GitLab variables and/or in the code) while `mender-convert` is `2.2.x`, hence still being published from a verified and reviewed branch. This is how I have done it previously.

Hmm, I see. But how did the release-job show up then? It didn't with me.


> @oleorhagen Alternatively, I would have extended the current only regex to add the `-buildXX` suffix. In any case what I want to avoid is publishing from arbitrary branches.

This is a fine compromise for me. I'll leave this as is for the day though, and revert, and extend when I'm done releasing.

**Comment by lluiscampos** [comment]
> > @oleorhagen I see. But `MENDER_VERSION` can still be `<release>-build'n'` (in the GitLab variables and/or in the code) while `mender-convert` is `2.2.x`, hence still being published from a verified and reviewed branch. This is how I have done it previously.
> 
> Hmm, I see. But how did the release-job show up then? It didn't with me.

Building from mender-convert `2.2.x` or from `2.2.1-build3`?

> 
> > @oleorhagen Alternatively, I would have extended the current only regex to add the `-buildXX` suffix. In any case what I want to avoid is publishing from arbitrary branches.
> 
> This is a fine compromise for me. I'll leave this as is for the day though, and revert, and extend when I'm done releasing.

:ok_hand:

**Comment by oleorhagen** [comment]
> Building from mender-convert `2.2.x` or from `2.2.1-build3`?

Ahh, I see. So it would have been okay building from the branch here? (I know they're the same sha).

I think I already know the answer here

**Comment by oleorhagen** [comment]
@lluiscampos this also?

**Comment by lluiscampos** [comment]
@oleorhagen :+1:

**Pull request merged**
