### PR TITLE
Next

### PR DESCRIPTION
**Pull request by Anil9860**
I used 
"sudo git clone -b next git@github.com:mendersoftware/mender-convert.git"
 this command to clone the files but its showing me 
----------->
"Cloning into 'mender-convert'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
root@ubuntu-anil-pc:/media/"

like this. what i have to do?

### CODE REVIEW

**Comment by drewmoseley** [comment]
Hi @Anil9860  it looks like you need to setup your githup profile with your ssh keys: https://help.github.com/en/articles/connecting-to-github-with-ssh

Alternatively, you can clone with the following URL which uses http-based authentication: https://github.com/mendersoftware/mender-convert.git

**Comment by drewmoseley** [comment]
Hi @Anil9860 the tenant token is if you plan on using hosted mender.

I can't tell from the above why it is not liking your options. I suspect something got mis-typed when you did it here.  Can you follow up over email with me? drew.moseley@northern.tech

Please provide the contents of the entire shell session that is failing.

**Comment by Anil9860** [comment]
Hello Drew,
i am trying to do the FOTA for BBB using mender. so basically what i have
to do is

$ git clone -b next git@github.com:mendersoftware/mender-convert.git
$ cd mender-convert
$ mkdir input
=> Place appropriate BBB/Debian image in input/ directory
$ ./scripts/bootstrap-rootfs-overlay-demo.sh --output-dir

till here there is a no problem, after this i have to run the next command
but there i have to paste token. so i am not getting what to paste there.
${PWD}/rootfs_overlay_demo --tenant-token *"<Paste token from Hosted
Mender>"*
$ ./docker-build

after  above step i have to follow below step for testing using SD card

$ MENDER_ARTIFACT_NAME=*<artifact-name-here> *./docker-mender-convert
--disk-image input/<image-name-here --config
configs/beaglebone_black_debian_sdcard_config --config
mender_local_config --overlay rootfs_overlay_demo/

in the above one which artifact name i have to keep there?




---

Best Regards,

Anil Dhanawade

Embedded Firmware Engineer

iBot Control Systems India pvt ltd Hyderabad.

Ground Floor, Vertex Corporate,, HITEC City, Hyderabad, Telangana 500081

Mobile No: +91-9561177624, 8686424158

http://www.iamibot.com

[image: linkedin.png]
<http://www.linkedin.com/in/anil-dhanawade9561177624>[image:
social-network-fb-logo-facebook-icon.png]
<http://www.facebook.com/AnilDhanawade9561177624>[image: app-icon2.png]
<https://www.instagram.com/>

**Comment by drewmoseley** [comment]
The bootstrap command need to specify an output directory so you need to run it as follows
```
$ ./scripts/bootstrap-rootfs-overlay-demo.sh --output-dir ~/mender-convert/output
```
or something like that.

If you are not using hosted mender you do not need to specify a tenant token. You will then need to edit the file _rootfs_overlay_demo/etc/mender/mender.conf_ and change the ServerURL setting to match the server you have setup.

The MENDER_ARTIFACT_NAME is the string you use to refer to the specific version of software you are building.  It can be as simple as a number or as complicated as you like.  I usually just use things like "release-1" and "release-2" for testing.  Once you go into production you will likely have a versioning policy that uses different naming but from Mender's perspective that's just a string value.

**Comment by Anil9860** [comment]
Hello Drew,
as you mentioned here i did it. so i am running my own server with my credentials(Login ID and password). so for that where i have to do the changes. because i have done the changes of 
 in Hone/mender-conver/rootfs_overlay_demo/etc/mender/mender.conf

{
  "InventoryPollIntervalSeconds": 5,
  "RetryPollIntervalSeconds": 30,
  "ServerURL": "https://localhost/",
  "UpdatePollIntervalSeconds": 5
}

i removed token because i am not using hosted mender, but here i am not getting that why i need to do the changes in the home directory. it should be done in the SD card, am i right?

Guide me on this.

**Comment by mirzak** [comment]
Can you please move this discussion to hub.mender.io. More people will see it there and can provide assistance.

I will make sure to follow-up to your questions.

**Comment by Anil9860** [comment]
OK Mirzak, no problem.

**Pull request closed without merging**
