### PR TITLE
2.0.x cherry picks

### PR DESCRIPTION
**Pull request by mirzak**
@kacf @lluiscampos @drewmoseley , do you agree that we should cherry-pick all 3 here?

### CODE REVIEW

**Comment by drewmoseley** [comment]
Yeah, no issue from me.

**Comment by kacf** [comment]
I think "Add support for GPT partition tables" should not be cherry-picked to 2.0.x. This is both a new feature, and a behavior change. I think we should save this for minor releases.

**Comment by mirzak** [comment]
> This is both a new feature, and a behavior change.

My reasoning for including (even if I agree that it is a new feature) is that there is no behavioral change for the majority of the cases (MBR images) and it actually fixes a problem for hardware/firmware that requires the image to be GPT for it to boot.

But as we are probably releasing `2.1.0` and `2.0.1` at the same time, I guess it does not hurt to save this for the "minor release".

**Comment by kacf** [comment]
I would argue for that, yes! :-)

**Pull request merged**
