### PR TITLE
Fix docker-mender-convert for paths with spaces

### PR DESCRIPTION
**Pull request by FSMaxB**

### CODE REVIEW

**Comment by FSMaxB** [comment]
Also there are more problems in the actual `mender-convert`, but I gave up and renamed my directories. But please look into fixing it. `mender-convert-functions.sh`'s `get_path` seems incorrect!

**Comment by FSMaxB** [comment]
(as well as several uses of `get_path`)

**Comment by apodogrocki** [comment]
@FSMaxB As to `get_path`, we will take a look at that.

**Comment by FSMaxB** [comment]
Sorry, I just did a quick change using the GitHub web ui. I changed the commit message now and did a force push.

**Pull request merged**
