### PR TITLE
[dependabot] Track dependencies of linkbot npm package

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
I don't think this is very important, really. But we are getting annoying security alerts for these, so better to just keep them up to date... right?

**Review by oleorhagen — APPROVED** [review]

**Review by mzedel — APPROVED** [review]
Just fyi: we will still get the security notes - as they are issued more frequently than the dependabot check will be run... (as is the case for the GUI repo e.g.)

**Comment by lluiscampos** [comment]
> Just fyi: we will still get the security notes - as they are issued more frequently than the dependabot check will be run... (as is the case for the GUI repo e.g.)

Yeah, I know. But at least on a week time they should disappear...

It is different in GUI repo where javascript code is actually in production, so some of the alerts might be very important to catch immediately.

**Comment by lluiscampos** [comment]
Stopping the build to save resources.

**Pull request merged**
