### PR TITLE
run-tests.sh: Update Ubuntu Rpi image to 20.04

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@oleorhagen It doesn't seem like the auto-updater is working for this image.

**Comment by oleorhagen** [comment]
> @oleorhagen It doesn't seem like the auto-updater is working for this image.

Hmm, I had a look, and it seems our script works fine:
```
url: 'http://downloads.raspberrypi.org/raspbian_lite/images/',
    imageName: 'raspbian_lite-2020-02-14',
    updated: '2020-02-13'
  }
]
We've got a new release! \o/
```
But it has some issues creating a PR:
```
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  master
  Working base is branch 'master'
  /usr/bin/git checkout --progress -B 9cc3354b-a46c-4774-99f9-a24233c41a38 HEAD
  Switched to a new branch '9cc3354b-a46c-4774-99f9-a24233c41a38'
  /usr/bin/git status --porcelain -unormal
  /usr/bin/git diff --quiet
  /usr/bin/git diff --quiet --staged
  Resetting working base branch 'master'
  /usr/bin/git checkout --progress master
  Switched to branch 'master'
  Your branch is up to date with 'origin/master'.
  /usr/bin/git reset --hard origin/master
  HEAD is now at 33767c8 Merge pull request #357 from mendersoftware/dependabot/submodules/tests/mender-image-tests-80bd053
  /usr/bin/git -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --unshallow origin create-pull-request/patch:refs/remotes/origin/create-pull-request/patch
  fatal: couldn't find remote ref create-pull-request/patch
  Pull request branch 'create-pull-request/patch' does not exist yet.
  /usr/bin/git checkout --progress -B create-pull-request/patch 9cc3354b-a46c-4774-99f9-a24233c41a38
  Switched to a new branch 'create-pull-request/patch'
  /usr/bin/git rev-list --right-only --count master...create-pull-request/patch
  0
  Branch 'create-pull-request/patch' is not ahead of base 'master' and will not be created
  /usr/bin/git branch --delete --force 9cc3354b-a46c-4774-99f9-a24233c41a38
  Deleted branch 9cc3354b-a46c-4774-99f9-a24233c41a38 (was 33767c8).
```
This relies on a 3rd part trigger. I will look into it next sprint :)

Thanks for the note

**Comment by lluiscampos** [comment]
@oleorhagen Seems like you found _an_ issue with the Raspbian OS image. But that is not the same image I am referring to in this PR: Ubuntu Server Rpi image.

In any case it is not urgent, let's look at it ~next sprint~ after the release.

**Comment by oleorhagen** [comment]
> @oleorhagen Seems like you found _an_ issue with the Raspbian OS image. But that is not the same image I am referring to in this PR: Ubuntu Server Rpi image.

Oh, sry. A bit  too quick there.

> 
> In any case it is not urgent, let's look at it ~next sprint~ after the release.

Agree!

**Comment by lluiscampos** [comment]
@oleorhagen Are you also going to approve this? :innocent:

**Comment by oleorhagen** [comment]
> @oleorhagen Are you also going to approve this? innocent

haha, sry

**Review by oleorhagen — APPROVED** [review]

**Pull request merged**
