### PR TITLE
test: Add a configuration with MENDER_GRUB_D_INTEGRATION turned off.

### PR DESCRIPTION
**Pull request by kacf**
This already broke once in our pipeline, so let's add this job
configuration so that we keep testing it.

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
Thank you for adding this. The changes look good to me :+1: 

I don't know why the runtime tests are all failing so miserably. I cannot spot anything obvious...

**Comment by kacf** [comment]
> I don't know why the runtime tests are all failing so miserably. I cannot spot anything obvious...

I think I know why. It's because Secure Boot is enabled for these tests, and when grub.d integration is turned off, it doesn't work, so QEMU doesn't boot. I'll find a workaround.

**Comment by kacf** [comment]
@lluiscampos: I attempted a fix now.

**Review by lluiscampos — APPROVED** [review]

**Review by lluiscampos — APPROVED** [review]

**Review by oleorhagen — APPROVED** [review]
@bboozzoo stop fucking with us!

**Comment by kacf** [comment]
> @bboozzoo stop fucking with us!

Haha, he doesn't even work there anymore!

**Comment by bboozzoo** [comment]
> @bboozzoo stop fucking with us!

hm? care to elaborate? what do you mean?

**Comment by oleorhagen** [comment]
> > @bboozzoo stop fucking with us!
> 
> hm? care to elaborate? what do you mean?

haha, oh shit, I meant to leave out a letter there to actually not ping you :see_no_evil: 

We we're just annoyed with Ubuntu decisions :p

**Comment by bboozzoo** [comment]
Ah, let me guess the test binary built on 22.04 doesn't work on 20.04? AFAIU openssl isn't the only problem, glibc version was also changed in 22.04, so versioned symbols won't be resolved.

**Comment by kacf** [comment]
Actually, more severe, binary built on 20.04 doesn't work on 22.04, and vice versa! Due to `libssl.so.1.1 != libssl.so.3`, and there is no compatibility package for it.

(I just checked btw, Fedora has a compatibility package)

**Comment by bboozzoo** [comment]
Sounds like fun. Out of curiosity, is it the mender binary that depends on openssl? IIRC Go does not link with openssl unless you're using boringcrypto.

**Comment by kacf** [comment]
@bboozzoo: We are use [OpenSSL C bindings](https://github.com/mendersoftware/openssl) to get to some esoteric features like hardware encryption. We don't use the Golang SSL code currently.

**Comment by lluiscampos** [comment]
@kacf I re-submitted in #474 (I couldn't force-push here) rebasing on top of latest master to fix the `mender-artifact` issue and dropping the Ubuntu downgrade patch. However the tests fail on the `scp` probing, see https://github.com/mendersoftware/mender-image-tests/pull/70#discussion_r965117116

Do you want me to take over the `mender-image-tests` PR too or do you want to manage it further (I would then close #474)?

**Comment by kacf** [comment]
We can just omit the scp fix. I pulled your branch and then force pushed that now, so you can close #474 I think.

**Review by lluiscampos — APPROVED** [review]

**Comment by kacf** [comment]
Finally!

**Pull request merged**
