### PR TITLE
Update mender-artifact to v3 and use LZMA

### PR DESCRIPTION
**Pull request by estenberg**

### CODE REVIEW

**Comment by estenberg** [comment]
MENDER_ARTIFACT_VERSION needs to be changed again to 3.0.0 in these two places once this tag has been created.

However, this is an intermediate step that enables testing of the beta.

**Comment by lluiscampos** [comment]
Thank you :+1:

**Comment by mirzak** [comment]
https://tracker.mender.io/browse/MEN-2497 :)

**Comment by estenberg** [comment]
FYI I backported these two commits to 1.1.x.
Was in doubt about the LZMA one due to the long compression time, but I figured Artifact size is more important.

**Pull request merged**
